layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
      - testrepo

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: markus-gerstel-mbcs-15a104a0
  # medium: @your_username
  # stackoverflow: your_user_id
  twitter: markusgerstel
  # youtube: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: Continuous Integration
    web_url: https://github.com/topics/continuous-integration
    image_url: https://jenkins.io/sites/default/files/jenkins_logo.png

  - name: DevOps
